FROM australia-southeast1-docker.pkg.dev/cpg-common/images/sv/sv-pipeline:2025-03-25-v1.0.2-hotfix-65eddd78

ARG VERSION=n_a

COPY compute_AFs.py /opt/sv-pipeline/05_annotation/scripts/compute_AFs.py

RUN chmod +x /opt/sv-pipeline/05_annotation/scripts/compute_AFs.py
