name: Linting
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: pre-commit
        run: |
          # pre-commit should install all the dependencies
          pip install pre-commit
          pre-commit run --all-files
